<?php
/**
 * This file is part of the Shieldon package.
 *
 * (c) Terry L. <contact@terryl.in>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 * 
 * php version 7.1.0
 * 
 * @category  Web-security
 * @package   Shieldon
 * @author    Terry Lin <contact@terryl.in>
 * @copyright 2019 terrylinooo
 * @license   https://github.com/terrylinooo/shieldon/blob/2.x/LICENSE MIT
 * @link      https://github.com/terrylinooo/shieldon
 * @see       https://shieldon.io
 */

declare(strict_types=1);

namespace Shieldon\Firewall\Component;

use Shieldon\Firewall\Component\ComponentProvider;
use Shieldon\Firewall\Component\DeniedTrait;
use Shieldon\Firewall\IpTrait;
use function Shieldon\Firewall\get_request;

use function implode;
use function preg_match;

/**
 * UserAgent component.
 */
class UserAgent extends ComponentProvider
{
    /**
     *   Public methods       | Desctiotion
     *  ----------------------|---------------------------------------------
     *   setIp                | Set an IP address.
     *   getIp                | Get current set IP.
     *   setRdns              | Set a RDNS record for the check.
     *   getRdns              | Get IP resolved hostname.
     *  ----------------------|---------------------------------------------
     */
    use IpTrait;

    /**
     *   Public methods       | Desctiotion
     *  ----------------------|---------------------------------------------
     *   setDeniedItems       | Add items to the blacklist pool.
     *   setDeniedItem        | Add an item to the blacklist pool.
     *   getDeniedItems       | Get items from the blacklist pool.
     *   getDeniedItem        | Get items from the blacklist pool.
     *   removeDeniedItem     | Remove a denied item if exists.
     *   removeDeniedItems    | Remove all denied items.
     *   hasDeniedItem        | Check if a denied item exists.
     *   getDenyWithPrefix    | Check if a denied item exists have the same prefix.
     *   removeDenyWithPrefix | Remove denied items with the same prefix.
     *   isDenied             | Check if an item is denied?
     *  ----------------------|---------------------------------------------
     */
    use DeniedTrait;

    /**
     * Constant
     */
    const STATUS_CODE = 84;

    /**
     * Robot's user-agent text.
     * 
     * @var string
     */
    private $userAgent = '';

    /**
     * Constructor.
     */
    public function __construct()
    {
        $this->userAgent = get_request()->getHeaderLine('user-agent');

        /**
         * Those robots are considered as bad behavior. 
         * Therefore we list them here.
         */
        $this->deniedList = [

            // Backlink crawlers
            'Ahrefs',     // http://ahrefs.com/robot/
            'roger',      // rogerbot (SEOMOZ)
            'moz.com',    // SEOMOZ crawlers
            'MJ12bot',    // Majestic crawlers
            'findlinks',  // http://wortschatz.uni-leipzig.de/findlinks
            'Semrush',    // http://www.semrush.com/bot.html
    
            // Web information crawlers
            'domain',     // Domain name information crawlers.
            'copyright',  // Copyright information crawlers.
    
            // Others
            'archive',    // Wayback machine


            // Monitorio
            // ----------------------------------------------
            '01h4x.com',
            '360Spider',
            '404checker',
            '404enemy',
            '80legs',
            'ADmantX',
            'AIBOT',
            'ALittle Client',
            'ASPSeek',
            'Abonti',
            'Aboundex',
            'Aboundexbot',
            'Acunetix',
            'AdsTxtCrawlerTP',
            'AfD-Verbotsverfahren',
            'AhrefsBot',
            'AiHitBot',
            'Aipbot',
            'Alexibot',
            'AllSubmitter',
            'Alligator',
            'AlphaBot',
            'Anarchie',
            'Anarchy',
            'Anarchy99',
            'Ankit',
            'Anthill',
            'Apexoo',
            'Aspiegel',
            'Asterias',
            'Atomseobot',
            'Attach',
            'AwarioRssBot',
            'AwarioSmartBot',
            'BBBike',
            'BDCbot',
            'BDFetch',
            'BLEXBot',
            'BackDoorBot',
            'BackStreet',
            'BackWeb',
            'Backlink-Ceck',
            'BacklinkCrawler',
            'Badass',
            'Bandit',
            'Barkrowler',
            'BatchFTP',
            'Battleztar Bazinga',
            'BetaBot',
            'Bigfoot',
            'Bitacle',
            'BlackWidow',
            'Black Hole',
            'Blackboard',
            'Blow',
            'BlowFish',
            'Boardreader',
            'Bolt',
            'BotALot',
            'Brandprotect',
            'Brandwatch',
            'Buck',
            'Buddy',
            'BuiltBotTough',
            'BuiltWith',
            'Bullseye',
            'BunnySlippers',
            'BuzzSumo',
            'CATExplorador',
            'CCBot',
            'CODE87',
            'CSHttp',
            'Calculon',
            'CazoodleBot',
            'Cegbfeieh',
            'CensysInspect',
            'CheTeam',
            'CheeseBot',
            'CherryPicker',
            'ChinaClaw',
            'Chlooe',
            'Citoid',
            'Claritybot',
            'Cliqzbot',
            'Cloud mapping',
            'Cocolyzebot',
            'Cogentbot',
            'Collector',
            'Copier',
            'CopyRightCheck',
            'Copyscape',
            'Cosmos',
            'Craftbot',
            'Crawling at Home Project',
            'CrazyWebCrawler',
            'Crescent',
            'CrunchBot',
            'Curious',
            'Custo',
            'CyotekWebCopy',
            'DBLBot',
            'DIIbot',
            'DSearch',
            'DTS Agent',
            'DataCha0s',
            'DatabaseDriverMysqli',
            'Demon',
            'Deusu',
            'Devil',
            'Digincore',
            'DigitalPebble',
            'Dirbuster',
            'Disco',
            'Discobot',
            'Discoverybot',
            'Dispatch',
            'DittoSpyder',
            'DnBCrawler-Analytics',
            'DnyzBot',
            'DomCopBot',
            'DomainAppender',
            'DomainCrawler',
            'DomainSigmaCrawler',
            'DomainStatsBot',
            'Domains Project',
            'Dotbot',
            'Download Wonder',
            'Dragonfly',
            'Drip',
            'ECCP/1.0',
            'EMail Siphon',
            'EMail Wolf',
            'EasyDL',
            'Ebingbong',
            'Ecxi',
            'EirGrabber',
            'EroCrawler',
            'Evil',
            'Exabot',
            'Express WebPictures',
            'ExtLinksBot',
            'Extractor',
            'ExtractorPro',
            'Extreme Picture Finder',
            'EyeNetIE',
            'Ezooms',
            'FDM',
            'FHscan',
            'FemtosearchBot',
            'Fimap',
            'Firefox/7.0',
            'FlashGet',
            'Flunky',
            'Foobot',
            'Freeuploader',
            'FrontPage',
            'Fuzz',
            'FyberSpider',
            'Fyrebot',
            'G-i-g-a-b-o-t',
            'GT::WWW',
            'GalaxyBot',
            'Genieo',
            'GermCrawler',
            'GetRight',
            'GetWeb',
            'Getintent',
            'Gigabot',
            'Go!Zilla',
            'Go-Ahead-Got-It',
            'GoZilla',
            'Gotit',
            'GrabNet',
            'Grabber',
            'Grafula',
            'GrapeFX',
            'GrapeshotCrawler',
            'GridBot',
            'HEADMasterSEO',
            'HMView',
            'HTMLparser',
            'HTTP::Lite',
            'HTTrack',
            'Haansoft',
            'HaosouSpider',
            'Harvest',
            'Havij',
            'Heritrix',
            'Hloader',
            'HonoluluBot',
            'Humanlinks',
            'HybridBot',
            'IDBTE4M',
            'IDBot',
            'IRLbot',
            'Iblog',
            'Id-search',
            'IlseBot',
            'Image Fetch',
            'Image Sucker',
            'IndeedBot',
            'Indy Library',
            'InfoNaviRobot',
            'InfoTekies',
            'Intelliseek',
            'InterGET',
            'InternetSeer',
            'Internet Ninja',
            'Iria',
            'Iskanie',
            'IstellaBot',
            'JOC Web Spider',
            'JamesBOT',
            'Jbrofuzz',
            'JennyBot',
            'JetCar',
            'Jetty',
            'JikeSpider',
            'Joomla',
            'Jorgee',
            'JustView',
            'Jyxobot',
            'Kenjin Spider',
            'Keybot Translation-Search-Machine',
            'Keyword Density',
            'Kinza',
            'Kozmosbot',
            'LNSpiderguy',
            'LWP::Simple',
            'Lanshanbot',
            'Larbin',
            'Leap',
            'LeechFTP',
            'LeechGet',
            'LexiBot',
            'Lftp',
            'LibWeb',
            'Libwhisker',
            'LieBaoFast',
            'Lightspeedsystems',
            'Likse',
            'LinkScan',
            'LinkWalker',
            'Linkbot',
            'LinkextractorPro',
            'LinkpadBot',
            'LinksManager',
            'LinqiaMetadataDownloaderBot',
            'LinqiaRSSBot',
            'LinqiaScrapeBot',
            'Lipperhey',
            'Lipperhey Spider',
            'Litemage_walker',
            'Lmspider',
            'Ltx71',
            'MFC_Tear_Sample',
            'MIDown tool',
            'MIIxpc',
            'MJ12bot',
            'MQQBrowser',
            'MSFrontPage',
            'MSIECrawler',
            'MTRobot',
            'Mag-Net',
            'Magnet',
            //'Mail.RU_Bot',
            'Majestic-SEO',
            'Majestic12',
            'Majestic SEO',
            'MarkMonitor',
            'MarkWatch',
            'Mass Downloader',
            'Masscan',
            'Mata Hari',
            'MauiBot',
            'Mb2345Browser',
            'MeanPath Bot',
            'Meanpathbot',
            'Mediatoolkitbot',
            'MegaIndex.ru',
            'Metauri',
            'MicroMessenger',
            'Microsoft Data Access',
            'Microsoft URL Control',
            'Minefield',
            'Mister PiX',
            'Moblie Safari',
            'Mojeek',
            'Mojolicious',
            'MolokaiBot',
            'Morfeus Fucking Scanner',
            'Mozlila',
            'Mr.4x3',
            'Msrabot',
            'Musobot',
            'NICErsPRO',
            'NPbot',
            'Name Intelligence',
            'Nameprotect',
            'Navroad',
            'NearSite',
            'Needle',
            'Nessus',
            'NetAnts',
            'NetLyzer',
            'NetMechanic',
            'NetSpider',
            'NetZIP',
            'Net Vampire',
            'Netcraft',
            'Nettrack',
            'Netvibes',
            'NextGenSearchBot',
            'Nibbler',
            'Niki-bot',
            'Nikto',
            'NimbleCrawler',
            'Nimbostratus',
            'Ninja',
            'Nmap',
            'Nuclei',
            'Nutch',
            'Octopus',
            'Offline Explorer',
            'Offline Navigator',
            'OnCrawl',
            'OpenLinkProfiler',
            'OpenVAS',
            'Openfind',
            'Openvas',
            'OrangeBot',
            'OrangeSpider',
            'OutclicksBot',
            'OutfoxBot',
            'PECL::HTTP',
            'PHPCrawl',
            'POE-Component-Client-HTTP',
            'PageAnalyzer',
            'PageGrabber',
            'PageScorer',
            'PageThing.com',
            'Page Analyzer',
            'Pandalytics',
            'Panscient',
            'Papa Foto',
            'Pavuk',
            'PeoplePal',
            'Petalbot',
            'Pi-Monster',
            'Picscout',
            'Picsearch',
            'PictureFinder',
            'Piepmatz',
            'Pimonster',
            'Pixray',
            'PleaseCrawl',
            'Pockey',
            'ProPowerBot',
            'ProWebWalker',
            'Probethenet',
            'Proximic',
            'Psbot',
            'Pu_iN',
            'Pump',
            'PxBroker',
            'PyCurl',
            'QueryN Metasearch',
            'Quick-Crawler',
            'RSSingBot',
            'RankActive',
            'RankActiveLinkBot',
            'RankFlex',
            'RankingBot',
            'RankingBot2',
            'Rankivabot',
            'RankurBot',
            'Re-re',
            'ReGet',
            'RealDownload',
            'Reaper',
            'RebelMouse',
            'Recorder',
            'RedesScrapy',
            'RepoMonkey',
            'Ripper',
            'RocketCrawler',
            'Rogerbot',
            'SBIder',
            'SEOkicks',
            'SEOkicks-Robot',
            'SEOlyticsCrawler',
            'SEOprofiler',
            'SEOstats',
            'SISTRIX',
            'SMTBot',
            'SalesIntelligent',
            'ScanAlert',
            'Scanbot',
            'ScoutJet',
            'Scrapy',
            'Screaming',
            'ScreenerBot',
            'ScrepyBot',
            'Searchestate',
            'SearchmetricsBot',
            'Seekport',
            'SeekportBot',
            'SemanticJuice',
            'Semrush',
            'SemrushBot',
            'SentiBot',
            'SenutoBot',
            'SeoSiteCheckup',
            'SeobilityBot',
            'Seomoz',
            'Shodan',
            'Siphon',
            'SiteCheckerBotCrawler',
            'SiteExplorer',
            'SiteLockSpider',
            'SiteSnagger',
            'SiteSucker',
            'Site Sucker',
            'Sitebeam',
            'Siteimprove',
            'Sitevigil',
            'SlySearch',
            'SmartDownload',
            'Snake',
            'Snapbot',
            'Snoopy',
            'SocialRankIOBot',
            'Sociscraper',
            'Sogou web spider',
            'Sosospider',
            'Sottopop',
            'SpaceBison',
            'Spammen',
            'SpankBot',
            'Spanner',
            'Spbot',
            'Spinn3r',
            'SputnikBot',
            'Sqlmap',
            'Sqlworm',
            'Sqworm',
            'Steeler',
            'Stripper',
            'Sucker',
            'Sucuri',
            'SuperBot',
            'SuperHTTP',
            'Surfbot',
            'SurveyBot',
            'Suzuran',
            'Swiftbot',
            'Szukacz',
            'T0PHackTeam',
            'T8Abot',
            'Teleport',
            'TeleportPro',
            'Telesoft',
            'Telesphoreo',
            'Telesphorep',
            'TheNomad',
            'The Intraformant',
            'Thumbor',
            'TightTwatBot',
            'Titan',
            'Toata',
            'Toweyabot',
            'Tracemyfile',
            'Trendiction',
            'Trendictionbot',
            'True_Robot',
            'Turingos',
            'Turnitin',
            'TurnitinBot',
            'TwengaBot',
            'Twice',
            'Typhoeus',
            'URLy.Warning',
            'URLy Warning',
            'UnisterBot',
            'Upflow',
            'V-BOT',
            'VB Project',
            'VCI',
            'Vacuum',
            'Vagabondo',
            'VelenPublicWebCrawler',
            'VeriCiteCrawler',
            'VidibleScraper',
            'Virusdie',
            'VoidEYE',
            'Voil',
            'Voltron',
            'WASALive-Bot',
            'WBSearchBot',
            'WEBDAV',
            'WISENutbot',
            'WPScan',
            'WWW-Collector-E',
            'WWW-Mechanize',
            'WWW::Mechanize',
            'WWWOFFLE',
            'Wallpapers',
            'Wallpapers/3.0',
            'WallpapersHD',
            'WeSEE',
            'WebAuto',
            'WebBandit',
            'WebCollage',
            'WebCopier',
            'WebEnhancer',
            'WebFetch',
            'WebFuck',
            'WebGo IS',
            'WebImageCollector',
            'WebLeacher',
            'WebPix',
            'WebReaper',
            'WebSauger',
            'WebStripper',
            'WebSucker',
            'WebWhacker',
            'WebZIP',
            'Web Auto',
            'Web Collage',
            'Web Enhancer',
            'Web Fetch',
            'Web Fuck',
            'Web Pix',
            'Web Sauger',
            'Web Sucker',
            'Webalta',
            'WebmasterWorldForumBot',
            'Webshag',
            'WebsiteExtractor',
            'WebsiteQuester',
            'Website Quester',
            'Webster',
            'Whack',
            'Whacker',
            'Whatweb',
            'Who.is Bot',
            'Widow',
            'WinHTTrack',
            'WiseGuys Robot',
            'Wonderbot',
            'Woobot',
            'Wotbox',
            'Wprecon',
            'Xaldon WebSpider',
            'Xaldon_WebSpider',
            'Xenu',
            'YoudaoBot',
            'Zade',
            'Zauba',
            'Zermelo',
            'Zeus',
            'Zitebot',
            'ZmEu',
            'ZoomBot',
            'ZoominfoBot',
            'ZumBot',
            'ZyBorg',
            'adscanner',
            'archive.org_bot',
            'arquivo-web-crawler',
            'arquivo.pt',
            'autoemailspider',
            'backlink-check',
            'cah.io.community',
            'check1.exe',
            'clark-crawler',
            'coccocbot',
            'cognitiveseo',
            'com.plumanalytics',
            'crawl.sogou.com',
            'crawler.feedback',
            'crawler4j',
            'dataforseo.com',
            'dataforseobot',
            'demandbase-bot',
            'domainsproject.org',
            'eCatch',
            'evc-batch',
            'facebookscraper',
            'gopher',
            'heritrix',
            'instabid',
            'internetVista monitor',
            'ips-agent',
            'isitwp.com',
            'iubenda-radar',
            'linkdexbot',
            'lwp-request',
            'lwp-trivial',
            'magpie-crawler',
            'meanpathbot',
            'mediawords',
            'muhstik-scan',
            'netEstate NE Crawler',
            'oBot',
            'page scorer',
            'pcBrowser',
            'plumanalytics',
            'polaris version',
            'probe-image-size',
            'ripz',
            's1z.ru',
            'satoristudio.net',
            'scalaj-http',
            'scan.lol',
            'seobility',
            'seocompany.store',
            'seoscanners',
            'seostar',
            'serpstatbot',
            'sexsearcher',
            'sitechecker.pro',
            'siteripz',
            'sogouspider',
            'sp_auditbot',
            'spyfu',
            'sysscan',
            'tAkeOut',
            'trendiction.com',
            'trendiction.de',
            'ubermetrics-technologies.com',
            'voyagerx.com',
            'webgains-bot',
            'webmeup-crawler',
            'webpros.com',
            'webprosbot',
            'x09Mozilla',
            'x22Mozilla',
            'xpymep1.exe',
            'zauba.io',
            'zgrab',

            //'Baiduspider',
            //'Baiduspider-image',
            //'Baiduspider-video',
            //'Baiduspider-news',
            //'Baiduspider-favo',
            //'Baiduspider-cpro',
            //'Baiduspider-ads',
            //'Baidu',
            'Riddler',
            'FlipboardProxy',
            'trovitBot',
            // ----------------------------------------------
            
        ];
    }

    /**
     * {@inheritDoc}
     * 
     * @return bool
     */
    public function isDenied(): bool
    {
        if (!empty($this->deniedList)) {

            //$deniedList = $this->deniedList;
            //array_walk($deniedList, 'preg_quote');
            
            $deniedList = [];
            foreach ($this->deniedList as $agent) {
                $deniedList[] = preg_quote($agent, '/');
            }

            if (preg_match('/(' . implode('|', $deniedList). ')/i', $this->userAgent, $matches)) {
                return true;
            }
        }

        if ($this->strictMode) {

            // If strict mode is on, this value can not be empty.
            if (empty($this->userAgent)) {
                return true;
            }
        }

        return false;
    }

    /**
     * {@inheritDoc}
     * 
     * @return int
     */
    public function getDenyStatusCode(): int
    {
        return self::STATUS_CODE;
    }
}
