<?php

return [
    'deny_title' => 'Доступ запрещен',
    'deny_heading' => 'Доступ запрещен',
    'deny_message' => 'Используемый вами IP-адрес заблокирован.',
    'limit_title' => 'Пожалуйста, подождите',
    'limit_heading' => 'Пожалуйста, подождите',
    'limit_message' => 'Доступ к этой странице ограничен по количеству одновременных подключений. Пожалуйста, подождите.',
    'stop_title' => 'Пожалуйста, подтвердите что вы не робот',
    'stop_heading' => 'Обнаружено необычное поведение',
    'stop_message' => 'Пожалуйста, заполните CAPTCHA, чтобы подтвердить, что вы человек.',
    'stop_submit' => 'Отправить',
    'credit' => 'Этот сайт защищен проектом с открытым исходным кодом {0}.',
    'lineup_info' => 'Количество пользователей впереди вас: {0}',
    'online_info' => 'Пользователей онлайн: {0}',
    'keepalive_info' => 'После входа у каждого пользователя есть {0} секунд для просмотра этой страницы.',
    'messenger_notification_subject' => 'Уведомление по IP: {0} !',

    // @since 0.1.7
    'messenger_text_ip' => 'IP',
    'messenger_text_rdns' => 'RDNS',
    'messenger_text_time' => 'Время',
    'messenger_text_timezone' => 'Часовой пояс',
    'messenger_text_cpu' => 'CPU потребление',
    'messenger_text_memory' => 'Потребление памяти',
    'messenger_text_reason' => 'Прична',
    'messenger_text_system' => 'Состояние системы',
    'messenger_text_reason_code_1' => 'Слишком много сеансов.',
    'messenger_text_reason_code_2' => 'Слишком много обращений.',
    'messenger_text_reason_code_3' => 'Невозможно создать файлы cookie JS.',
    'messenger_text_reason_code_4' => 'Пустой referrer.',
    'messenger_text_reason_code_11' => 'Лимит в день достигнут.',
    'messenger_text_reason_code_12' => 'Достигнуто ограничение в час.',
    'messenger_text_reason_code_13' => 'Достигнуто ограничение в минуту.',
    'messenger_text_reason_code_14' => 'Достигнуто ограничение в секунду.',
    'messenger_text_handle' => 'Handle',
    'messenger_text_handle_type_1' => 'Этот IP-адрес был навсегда заблокирован в текущем цикле данных до сброса цикла данных.',
    'messenger_text_handle_type_2' => 'Этот IP-адрес был помещен в список DROP iptables до перезагрузки сервера.',

    'messenger_text_mail_subject' => 'Уведомление от брандмауэра Shieldon.',
];
